{% set name = "alpaca-py" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alpaca_py-{{ version }}.tar.gz
  sha256: 8a90e27f0bbe33cf7e9f5b5d0c40098bbca5723f4a3a899934ec61c65b53222b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.4.2
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - requests >=2.30.0,<3.0.0
    - pydantic >=2.0.3,<3.0.0
    - pandas >=1.5.3
    - msgpack-python >=1.0.3,<2.0.0
    - websockets >=10.4
    - sseclient-py >=1.7.2,<2.0.0

test:
  imports:
    - alpaca
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alpacahq/alpaca-py
  summary: The Official Python SDK for Alpaca APIs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sanurielf
    - hiohiohio
