{% set name = "alpaca-py" %}
{% set version = "0.43.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alpaca_py-{{ version }}.tar.gz
  sha256: 3f1d657327b7da13795b2c9839e486e933c495091a261bcbd577f6db3df41523

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.4.2
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - requests >=2.30.0,<3.0.0
    - pydantic >=2.0.3,<3.0.0
    - pandas >=1.5.3
    - msgpack-python >=1.0.3,<2.0.0
    - websockets >=10.4
    - sseclient-py >=1.7.2,<2.0.0

test:
  imports:
    - alpaca
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alpacahq/alpaca-py
  summary: The Official Python SDK for Alpaca APIs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sanurielf
    - hiohiohio
